version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    env_file:
      - server/.env
    environment:
      FT_PORT: 80
      DEBUG: 42:*
    image: fortee2
    network_mode: host
